project:
  type: website
  output-dir: docs

website:
  title: "SentinelKilnDB"
  description: "A Large-Scale Dataset for Brick Kiln Detection in South Asia"
  
  navbar:
    background: white
    foreground: dark
    title: "SentinelKilnDB"
    left:
      - href: index.qmd
        text: "Home"
      - href: dataset.qmd
        text: "Dataset"
      - href: benchmark.qmd
        text: "Benchmark"
      - href: applications.qmd
        text: "Applications"
    right:
      - icon: github
        href: "https://github.com/rishabh-mondal/NeurIPS_2025"
      - text: "Download"
        href: "https://kaggle.com/datasets/3eb8e7201b14b158ed841718cb777c5b94a6a6375aaa8499c7376ec831f8d879"

  page-footer:
    center: "© 2025 SentinelKilnDB - Accepted at NeurIPS 2025"

format:
  html:
    theme: 
      - flatly
      - custom.scss
    css: styles.css
    toc: false
    smooth-scroll: true
    anchor-sections: true